pengutronix/meta-ptx

classes/genimage.bbclass
This fixes severals typos.
Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>
=> classes: genimage: fix typos

recipes-core/dt-utils/dt-utils_2016.12.0.bb, recipes-core/dt-utils/dt-utils_2017.03.0.bb
=> dt-utils: update to 2017.03.0

recipes-devtools/memtool/memtool_2018.03.0.bb
=> add recipe for memtool

recipes-bsp/barebox/barebox_2017.10.0.bb, recipes-bsp/barebox/barebox_2018.04.0.bb
=> barebox: update to 2018.04.0

recipes-devtools/genimage/genimage_10.bb, recipes-devtools/genimage/genimage_9.bb
=> genimage: update to v10

conf/layer.conf
=> conf: layer: add 'thud' to LAYERSERIES_COMPAT

recipes-bsp/barebox/barebox_2018.05.0.bb, recipes-bsp/barebox/barebox_2018.12.0.bb
=> barebox: update to 2018.12.0

conf/distro/ptx.conf
=> distro: ptx.conf: synchronize with upstream thud (2.6) poky distro state

classes/bootspec.bbclass
If no devicetree is used, we add a dummy entry 'default' for a writing a
single entry.
When iterating over dtb's and hitting the 'default' entry, we also
skip writing the 'devicetree' line.
=> classes/bootspec: support for machines not using devicetrees (e.g. x86)

conf/layer.conf
=> conf: layer: add 'warrior' to LAYERSERIES_COMPAT

recipes-bsp/barebox/barebox_2018.12.0.bb, recipes-bsp/barebox/barebox_2019.03.0.bb
=> barebox: update to 2019.03.0

conf/distro/ptx.conf
=> distro/ptx.conf: update distro version to 2.7 (warrior)

classes/genimage.bbclass
This should fix some issues in the genimage class inline documentation revealed during working with it.
=> genimage.bbclass documentation fixes

recipes-devtools/genimage/genimage_10.bb, recipes-devtools/genimage/genimage_11.bb
=> genimage: update to v11

conf/layer.conf
=> conf: layer: add 'zeus' to LAYERSERIES_COMPAT

classes/genimage.bbclass
This is a collection of some minor updates to the genimage class.
=> Minor updates on genimage class

recipes-devtools/genimage/genimage_11.bb, recipes-devtools/genimage/genimage_12.bb
=> genimage: update to v12

classes/genimage.bbclass
This adds several fixes and enhancements to the genimage.bbclass including:
* build dependency fixes
* adapted task and stamp handling
* directory cleanup handling
* task simplification
* fixed config marker replacement handling
* added sstate handling
=> Rework genimage.bbclass

conf/layer.conf
=> conf: layer: add 'dunfell' to LAYERSERIES_COMPAT

README, README.md
This hasn't been touched for a while. This corrects some things and converts file to Markdown for making it more readable on GitHub
=> Rework of README and rename to README.md

conf/distro/ptx.conf
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>
=> distro/ptx.conf: update to dunfell (3.1)

classes/genimage.bbclass
This is a backport of 9eaa29b7d0f0ffb11acb8e4b50107eeaaaf0cf71 needed since ``dunfell-dunfell-23.0.6``.
=> genimage: add deploy task after genimage

conf/distro/ptx.conf, conf/layer.conf
And another small fix that was applied similar to hardknott's meta-poky.
Note that this fixes CI building for master.
=> Update LAYERSERIES_COMPAT for hardknott

recipes-bsp/barebox/barebox_2020.11.0.bb, recipes-bsp/barebox/barebox_2021.03.0.bb
Signed-off-by: Vivien Didelot <vdidelot@pbsc.com>
=> barebox: update to 2021.03.0

conf/layer.conf
This should make the layer checks happy.
=> conf: layer: add LAYERDEPENDS_ptx = "core"

recipes-devtools/confuse/confuse_2.7.bb, recipes-devtools/genimage/genimage.inc
Signed-off-by: Soren Andersen <san@skov.com>
=> confuse and genimage: Add nativesdk to BBCLASSEXTEND

classes/genimage.bbclass
An alternative to fixing the accumulation of old images reported in
PR #78. Tested lightly with changing combinations of .config files, input images and both, and seems to DTRT.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>
=> genimage.bbclass: clean ${B} completely before building

classes/bootspec.bbclass
The purpose of this PR is to add the support for external (BSP) device tree's.
Those device tree's can be build by a BSP recipes using the Poky devicetree.bbclass.
=> Add bootspec support for external device tree's

.github/workflows/meta-ptx.yml, recipes-bsp/barebox/barebox.inc
Cherry-picks commit that brought in GitHub Actions testing workflow and adapt to dunfell branch.
=> Enable testing of 'dunfell' branch

conf/distro/ptx.conf
* Update distro codename and version
* remove `reproducible_build` class usage
* bump `LOCALCONF_VERSION` version
=> update ptx distro to honister

recipes-devtools/genimage/genimage.inc
This makes it easier to find the upstream repository.
=> genimage: provide HOMEPAGE

.github/workflows/meta-ptx.yml, recipes-devtools/microcom/microcom_2019.01.0.bb
Pengutronix' microcom comes with more features than busybox' microcom, e.g. "telnet mode" as specified in rfc2217.
=> microcom: new recipe

recipes-bsp/barebox/barebox_2021.03.0.bb, recipes-bsp/barebox/barebox_2022.03.0.bb
=> barebox: update to 2022.03.0

conf/distro/ptx.conf
=> distro: ptx: update to kirkstone

conf/layer.conf
Keep compatibility to 'kirkstone' first of all.
=> conf: layer: add 'langdale' to LAYERSERIES_COMPAT

recipes-devtools/genimage/genimage_15.bb, recipes-devtools/genimage/genimage_16.bb
Among other features this new release brings (according to the git log):
- F2FS support
- Firmware Image Package (FIP) support
=> genimage: bump version to v16

conf/layer.conf
=> conf: layer: add 'mickledore' to LAYERSERIES_COMPAT

conf/distro/ptx.conf
Remove useless variable indirection.
While at it, also fix and add comments
=> Simplify ptx distro

recipes-graphics/platsch/platsch_2024.08.0.bb, recipes-graphics/platsch/platsch_git.bb
* moved to GitHub
* use a versioned recipe for the release
* move from autotools to meson
* add libplatsch package for shared library
=> platsch: update to 2024.08.0
