classes/bootspec.bbclass

The STAGING_KERNEL_BUILDDIR must be populated in order to run
get_kernelversion_file() properly on it.
To achieve this, we add a dependency on kernels do_shared_workdir task
before building the rootfs.

classes/bootspec: ensure STAGING_KERNEL_BUILDDIR is populated

---

classes/bootspec.bbclass

Please consider cherry-picking this commit for the rocko branch as well.

classes/bootspec: use regular file instead of symlink for 'devicetree' entry

---

conf/layer.conf

Setting this variable is used since sumo to track layer compatibility
and active layer maintanance.
Setting this will prevent from utriggering a warning and is required for
Yocto Project Compatible version 2 standard.

conf: layer: set LAYERSERIES_COMPAT for this layer

---

classes/bootspec.bbclass

This pull request fixing the bug "Overwriting of Variable BOOTSPEC_OPTIONS[doc] #12"
Signed-off-by: Eugen Wiens <eugen.wiens@jumo.net>

Fixing Overwriting of Variable BOOTSPEC_OPTIONS[doc]

---

recipes-core/dt-utils/dt-utils/src-fix-compilation-for-glibc-version-2.27.9000-36.f.patch
recipes-core/dt-utils/dt-utils_2018.05.0.bb

Jenkins test build failed on master because of being incompatible with recent glibc version.
Add this patch from upstream dt-utils to fix this.

dt-utils: fix compilation with newer glibc version

---

recipes-core/dt-utils/dt-utils_2018.05.1.bb
recipes-core/dt-utils/dt-utils_2019.01.0.bb

Please consider backporting this update at least to the "thud" branch as well.

dt-utils: update to 2019.01.0

---

recipes-bsp/barebox/barebox.inc

Both lex/yacc or compatibles are now dependencies of the barebox build
process, same as the kernel's. They are used since https://github.com/saschahauer/barebox/commit/273dbe5f87de8d6129a68ad40e87922fb6e783b6 contained
in barebox v2019.02.0 for generating the Kconfig lexer and parser.
Adding `flex-native` and `bison-native` to `DEPENDS` addresses this and fixes
the currently failing barebox v2019.02.0 `do_configure` stage:
| DEBUG: Executing shell function do_configure
| NOTE: make CROSS_COMPILE=arm-ptx-linux-gnueabi- oldconfig
|   YACC    scripts/kconfig/zconf.tab.c
| /bin/sh: 1: bison: not found
| scripts/Makefile.lib:194: recipe for target 'scripts/kconfig/zconf.tab.c' failed
| make[1]: *** [scripts/kconfig/zconf.tab.c] Error 127
| Makefile:416: recipe for target 'oldconfig' failed
| …

barebox: add bison and flex build dependencies

---

classes/genimage.bbclass

Depending on 'do_build' made a genimage recipe fail as the implicitely used
'staging.bbclass' tried to include the 'libgcc' package as well as the 'libgcc-
initial' package which contain conflicting files:
ERROR: <RECIPENAME>-<VERSION> do_genimage: The file /usr/lib/<ARCH>-<DISTRO>-<ABI>/8.3.0/libgcc.a is installed by both libgcc-initial and libgcc, aborting
ERROR: <RECIPENAME>-<VERSION> do_genimage:
ERROR: <RECIPENAME>-<VERSION> do_genimage: Function failed: extend_recipe_sysroot
ERROR: Logfile of failure stored in: <PATH_TO_BUILD_DIR>/tmp/work/<TUNEARCH>/<RECIPENAME>/<VERSION>/temp/log.do_genimage.19094
ERROR: Task (<PATH_TO_BSP_DIR>/<META-LAYER>/recipes-core/images/<RECIPENAME>.bb:do_genimage) failed with exit code '1'
'staging.bbclass' is responsible for filling a recipe's individual …

classes: genimage: depend on a different task of the used fs-image

---

recipes-bsp/barebox/barebox.inc
recipes-bsp/barebox/barebox_2019.03.0.bb
recipes-bsp/barebox/barebox_2019.05.0.bb

Barebox' commit 0bb285926777 ("LICENSES: adopt Linux-like LICENSES directory
structure") which is part of barebox >= v2019.04.0 modified the file "COPYING"
so that its md5 hash had to be adjusted in the license information.
Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>

barebox: update to v2019.05.0

---

classes/bootspec.bbclass

With the latest kernels like on arm64 machines the dts are
located in subdirectories. We have to remove any prefixes
for the loader entries.
Signed-off-by: Michael Grzeschik <m.grzeschik@pengutronix.de>

bootspec: fix loader entry for dtbs in subdirs

---

recipes-bsp/barebox/barebox.inc

Only add '.yocto-defaultenv' if it isn't already set.
Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>

barebox: fix CONFIG_DEFAULT_ENVIRONMENT_PATH expansion

---

conf/distro/ptx.conf

Remove deprecated DISTRO_FEATURES_LIBC according to upstream poky commit
5eb53830942141bfe57251dffecda36df90a62c1

distro/ptx.conf: align with poky zeus

---

recipes-core/dt-utils/dt-utils.inc

PN may contain common prefixes as -native or nativesdk- and is thus
inappropriate for SRC_URI. Replace by BPN which has these prefixes
removed.
This also fixes QA issue:
| do_package_qa: QA Issue: dt-utils: SRC_URI uses PN not BPN [src-uri-bad]

dt-utils: replace PN by BPN in SRC_URI

---

conf/distro/ptx.conf

Setting a custom TARGET_VENDOR will not have any benefit here except for
having a 'ptx'-named toolchain generated. But instead it will prevent us
from allowing to reuse standard/common sstate cache when having this distro
enabled.

distro/ptx.conf: do not set special TARGET_VENDOR

---

conf/distro/ptx.conf
recipes-core/packagegroups/packagegroup-core-boot.bbappend

The ptx layer should not unconditionally manipulate any existing package
to be compatible with the default YP guidelines.
To have ptx-profile only active when 'ptx' distro is selected, we add it
via `DISTRO_EXTRA_RDEPENDS`. So it will make its way into images that use
`packagegroup-base`, which is recommended, anyway.

add ptx-profile package only when 'ptx' distro is active

---

recipes-bsp/barebox/barebox.inc

This:
* replaces `${S}` by `${B}` reflect the correct semantic meaning of the directory used
* adds `${DEPLOYDIR}` to deploy `[cleandirs]` to ensure packing only things just generated

barebox.inc: fix deploy and build dir handling

---

conf/distro/ptx.conf

Use the usrmerge DISTRO feature to get rid of historical separations of
/bin and /usr/bin (/lib and /usr/lib, etc.).

distro/ptx.conf: add 'usrmerge' to default distro features

---

recipes-core/dt-utils/dt-utils.inc

By default, all debug symbols will end up in runtime package ${PN}-dbg,
even if the binaries are split into several runtime packages.
In most cases it is not an issue to install all non-relevant debug package
unconditionally. But as the 'dt-utils' package provides the 'fdtdump'
utility that the 'dtc' package also provides, this would trigger a -dbg
package collision when attempting to install both any of the dt-utils runtime
package and any of the dtc runtime packages:
| Error: Transaction check error:
|   file /usr/bin/.debug/fdtdump conflicts between attempted installs of libdt-utils-dbg-2019.01.0-r0.corei7_64 and dtc-dbg-1.5.1-r0.corei7_64
To prevent this, we simply disable the default debug package split and
perform it on our own by splitting the debug symbols into a
runtime …

dt-utils: perform manual package split to avoid dbg package collisions

---

recipes-bsp/barebox/barebox.inc

With this option it is possible to specify the required images within a
machine.conf file. This is useful to prevent flooding the deploy/images
directory if the Barebox Multi-Image support is used.
Signed-off-by: Marco Felsch <m.felsch@pengutronix.de>

barebox: add BAREBOX_IMAGES option

---

recipes-bsp/barebox/barebox.inc

The intention of the statement was to trigger a bberror if
no image could be found and ${BAREBOX_IMAGES} contains anything else
than the default glob '*.img'.
However, when the first expression evaluates to false and thus not
triggers the bberror, it will, in turn, let the script silently fail with
exit 1 which is not the intention here.

barebox: prevent BAREBOX_IMAGES check from failing unintentionally

---

recipes-bsp/barebox/barebox.inc

This implements the config fragment handling (used for kernel,
busybox and u-boot already) for barebox.
A config fragment can be added with
SRC_URI += "file://change.cfg"
and will be merged into the main configuration during `do_configure`.

barebox: allow using config fragments

---

recipes-bsp/barebox/barebox.inc

With setting BAREBOX_CONFIG, e.g
```
BAREBOX_CONFIG = "efi_defconfig"
```
we can now let barebox build without having to specify a 'defconfig'
file explicitly.
Also, change the warning about non-existing defconfig to be fatal and
provide in turn more helpful error message.

barebox: allows building standard defconfig

---

classes/genimage.bbclass

Commit 43f1cf2d3d4b ("image-artifact-names: introduce new bbclass and
move some variables into it") within poky moved the IMAGE_BASENAME from
the bitbake.conf to the image-artifact-names bbclass. Since genimage
uses IMAGE_BASENAME, inherit image-artifact-names.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>

genimage: inherit image-artifact-names

---

conf/distro/ptx.conf

No changes necessary otherwise since the poky config did not change much
from dunfell to gatesgarth.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>
Also requesting a backport to gatesgarth.

distro/ptx.conf: update to gatesgarth (3.2)

---

.github/workflows/meta-ptx.yml
README.md

Currently, this builds some packages provided by meta-ptx:
* barebox
* dt-utils
* genimage
The build requires to have a pre-populated sstate cache available that will be generated independently.

Add CI build using GitHub Actions

---

recipes-bsp/barebox/barebox_2019.05.0.bb
recipes-bsp/barebox/barebox_2020.11.0.bb

Also drop the legacy md5sum SRC_URI hash.

barebox: update to 2020.11.0

---

recipes-bsp/barebox/barebox.inc

Note that this also prevents errors when using 'externalsrc' class
which attempts to build out-of-tree by default.

barebox: enable out-of-tree builds

---

recipes-bsp/barebox/barebox.inc

```
Since v2020.11.0 barebox now supports a make BUILDSYSTEM_VERSION= option
that allows embedding a string into the barebox binary that is printed
to console and readable in barebox and Linux via imd.
This is useful because the barebox release may not reflect auxiliary
information like the configuration and the built-in environment.
Populate this variable with the git commit-ish of the git repository
containing the barebox recipe. If there's none, an empty string is
passed, which is the default behavior.
This can be enabled unconditionally for older barebox versions as well,
because unknown make variables are ignored.
Recipes that want to customize the version, can override
BAREBOX_BUILDSYSTEM_VERSION to their preferred value.
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
```

barebox: populate new BUILDSYSTEM_VERSION option

---

classes/genimage.bbclass

Instead of coding the deployment into the genimage task, use genimage as
a separate task which will only create the requested image, instead of
directly copying it into the ${DEPLOYDIR}. This is necessary since
fakeroot tasks add to the SSTATE, will try to record the uid and gid of
the files, however since PSEUDO_IGNORE_PATH was introduced into oe-core,
files within the deploy directory are ignored. This leads to an error
when trying to add files from the ${DEPLOYDIR} into the SSTATE:
```
WARNING: simple-sd-image-1.0-r0 do_genimage: KeyError in ./deploy-simple-sd-image
File: '/home/phoenix/build/YOCTO.BSP-Pengutronix-OP-TEE/meta/lib/oe/sstatesig.py', lineno: 592, function: OEOuthashBasic
0588:
0589:                update_hash("\n")
0590:
0591:            # Process this directory and all …
```

genimage: add deploy task after genimage

---

recipes-bsp/barebox/barebox.inc

Barebox expects the default environment files in the Source repository,
not the build repository. While this indicates a bug within barebox, we
should still allow includation of the default environment pending a fix.
Copy the default environment into the source directory instead of the
build directory.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>

barebox: unbreak defaultenv for master

---

classes/bootspec.bbclass

* remove True option from getVar() calls
* rename 'dtb' to 'dtbs' to reflect it holds multiple device trees
* do not strip .dtb ending from dtbs list and re-append it later on
Instead, strip it only when creating the .conf filename
* Use variable for conf filename to reduce code duplication

Some cleanup for the bootspec class

---

classes/genimage.bbclass

`DEPLOYDIR` is already set in the [deploy class](http://cgit.openembedded.org/openembedded-core/tree/meta/classes/deploy.bbclass?id=ecb038f14c0b91280ba1532ad94a6ebc64c70644#n1), but was not removed in
meta-ptx' commit 9eaa29b7d0f0. So clean it up now.

genimage: clean up after inheriting deploy class

---

recipes-core/dt-utils/dt-utils_2019.01.0.bb
recipes-core/dt-utils/dt-utils_2021.03.0.bb

Not sure what to do about the new `--enable-state-backward-compatibility` configure option, I guess every BSP maintainer would need to set this in a bbappend…?

dt-utils: update to 2021.03.0

---

conf/distro/ptx.conf

Poky config did not change from gatesgarth to hardknott.
Signed-off-by: Rouven Czerwinski <rouven@czerwinskis.de>

distro: update to hardknott

---

recipes-devtools/genimage/genimage_13.bb
recipes-devtools/genimage/genimage_14.bb

I am using this for the new android-sparse image type support, works
nicely.
Signed-off-by: Rouven Czerwinski <r.czerwinski@pengutronix.de>

genimage:  update to v14

---

classes/genimage.bbclass

The bbnote is currently emitted whenever genimage.config has at least
one line not containing @IMAGE@, i.e. effectively always. Fix the
logic so it is emitted if genimage.config doesn't have at least one
line containing @IMAGE@ as intended.

genimage.bbclass: fix grep usage in do_configure

---

classes/genimage.bbclass

Allow creating a `.bmap` metadata file for use with bmaptool.

genimage.bbclass: add bmaptool support

---

recipes-bsp/barebox/barebox.inc

If `BAREBOX_FIRMWARE_DIR` is set, barebox' `CONFIG_EXTRA_FIRMWARE_DIR` is set to its value. Note that the original value of `CONFIG_EXTRA_FIRMWARE_DIR` is overwritten in that case.
This allows setting the firmware search path directly without the need of copying firmware files around, e.g.:
```
BAREBOX_FIRMWARE_DIR = "${STAGING_DIR_TARGET}/firmware"
```
Currently (v2021.06.0) the imxcfg directive `signed_hdmi_firmware` does not consider `CONFIG_EXTRA_FIRMWARE_DIR`, so setting `BAREBOX_FIRMWARE_DIR` does not affect that. A possible workaround is:
```
BAREBOX_FIRMWARE_DIR = "${B}/firmware"
do_compile_prepend() {
mkdir -p ${BAREBOX_FIRMWARE_DIR}
cp ${DEPLOY_DIR_IMAGE}/signed_hdmi_imx8m.bin ${BAREBOX_FIRMWARE_DIR}
}
```
This works because `signed_hdmi_firmware` also expects the firmware in …

barebox: introduce BAREBOX_FIRMWARE_DIR

---

recipes-bsp/barebox/barebox.inc

Barebox' commit [[1]](https://github.com/saschahauer/barebox/commit/c008d836d8f47a75c9394137f44298771fce5001) contained in v2020.08.0 for the first time broke building
the userspace programs for the target system (``bareboxenv`` & Co.). Fix that by
offering the needed compiler flags not only in the present parameter
``TARGETCFLAGS``, but additionally in the newly introduced one ``userccflags``.
[1] [c008d836d8f4](https://github.com/saschahauer/barebox/commit/c008d836d8f47a75c9394137f44298771fce5001) ("scripts: use 'userprogs' to build programs for target")
Signed-off-by: Ulrich Ölmann <u.oelmann@pengutronix.de>

Fix Building barebox' Userspace Programs

---

classes/genimage.bbclass

`do_task[depends]` always expects dependencies in the form of `<recipe>:<task>`. This we missed for virtual/bootloader.

classes: genimage: fix dependency syntax in example

---

recipes-bsp/barebox/barebox.inc

As promised [here](https://github.com/pengutronix/meta-ptx/pull/74#issuecomment-883540834) clean up ``TARGETCFLAGS`` now as they are of no use anymore for current barebox releases (starting with v2020.08.0).

barebox: remove TARGETCFLAGS

---

recipes-bsp/barebox/barebox.inc

As ``pkgconfig`` is potentially nedded to build some of barebox' host tools (e.g. [``mxsimage``](https://git.pengutronix.de/cgit/barebox/tree/scripts/Makefile?h=v2021.11.0#n32) or [``imx-usb-loader``](https://git.pengutronix.de/cgit/barebox/tree/scripts/imx/Makefile?h=v2021.11.0#n4)) starting with [this](https://git.yoctoproject.org/cgit/cgit.cgi/poky/commit/?id=04b37f914ed1) Yocto commit we have to explicitely depend on it, otherwise the information that should have been gathered via ``pkg-config [...]`` is missing with the result that building those tools breaks.

barebox: add dependency on pkgconfig-native

---

classes/bootspec.bbclass

The idea to obtain the exact kernel version looked simple:
* Depend on do_shared_workdir task of kernel to have its source dir
populated
* run get_kernelversion_file() method to obtain the exact version string
This is fine as it allows to set the 'version' field and let the 'linux'
field point to the exact kernel version file.
However, reality hits you when attempting to build an eSDK.
In an eSDK, we have a set of fixed signatures and shared state artifacts
for each of them. However, do_shared_workdir is different as it is a
setscene-whitelisted task that always gets executed in dry run mode to
trigger depending tasks.
This means, despite it has a sort of setscene task, this task has no
data associated.
Now when using the bootspec class in an image that we build an eSDK
from, we make …

classes/bootspec: do not obtain kernel version from do_shared_workdir

---

classes/genimage.bbclass

It's useful to be able to pass extra custom options to genimage,
e.g. when one is building a newer genimage than the one defined in
meta-ptx to gain access to new features. For example, I wish to make
use of both --includepath (which is currently in genimage master) and
the just-proposed --configdump option.
Signed-off-by: Rasmus Villemoes <rasmus.villemoes@prevas.dk>

genimage.bbclass: allow recipe to pass extra options to genimage

---

recipes-bsp/barebox/barebox.inc
recipes-core/dt-utils/dt-utils.inc
recipes-devtools/genext2fs/genext2fs.inc
recipes-devtools/genimage/genimage.inc
recipes-devtools/memtool/memtool_2018.03.0.bb

OE-Core started in [9379f80f484f](https://git.openembedded.org/openembedded-core/commit/?id=9379f80f484f) to warn when it finds obsolete license identifiers as it was decided to standardize on SPDX license names. Use the conversion script introduced in OE-Core's commit [512cd4ca91bc](https://git.openembedded.org/openembedded-core/commit/?id=512cd4ca91bc) to silence the warnings.

Change LICENSE Entries to SPDX Identifiers

---

recipes-bsp/barebox/barebox.inc

In poky commit [4f4a5dc9](https://git.yoctoproject.org/poky/commit/?id=4f4a5dc9566171f0bee7c644c38335cba8b24a82) ("lzop: remove recipe from oe-core") lzop recipe and all dependencies on it were removed from oe-core because lzop is seen as deprecated and hasn't seen any release since 2017.
Thus remove dependency on it from barebox build, too.
This will potentially break use cases where lzop is still used for compression. Consider switching to different compression method then.

barebox: remove dependency on lzop-native

---

.github/workflows/meta-ptx.yml
conf/layer.conf
recipes-graphics/platsch/platsch_git.bb

platsch is a simple splash screen application meant to be run as pid 1.
Since platsch depends on libdrm >= 2.4.112 which is only available in langdale and newer, drop the layer's kirkstone compatibility.

Add platsch Recipe

---

conf/distro/ptx.conf

ipk package management is more light-weight than rpm and sufficient for most use cases. It requires less crude work arounds like package version translations due to character restrictions on Yocto's side.
This should be taken as a recommendation, since projects are encouraged to create their own distro (maybe copied from here) and PACKAGE_CLASSES is set in local.conf(.sample) by default.

distro: ptx: default to ipk package management

---

classes/genimage.bbclass

While genimage itself is MIT-licensed, images created with `genimage` using the `inherit genimage` should not be forced to be MIT-licensed. The standard for `.bbclass` files which set `LICENSE` is to set it with `?=` so the recipe can override it. Otherwise (with `=`) it isn't possible for the recipe to override it.
This commit is cherry-picked onto `master` from PR #115 as requested by @ejoerns.

genimage.bbclass: set LICENSE with '?=' to avoid forcing MIT license.

---

conf/layer.conf

poky/oe-core just released 'nanbield' and thus removed 'mickledore' compatibility.
While at it, remove 'langdale' which is out of support.

layer.conf: add 'nanbield' to LAYERSERIES_COMPAT

---

classes-recipe/genimage.bbclass

If not specified "install" installs the files with rwxr-xr-x permissions. Set the mode explicit to fix this.

classes: genimage: fix install file permissions

---

conf/layer.conf

OE-Core updated compatibility in upstream commit [`0e42326dfd6b ("layer.conf: Prepare for release, drop nanbield LAYERSERIES")`](https://github.com/openembedded/openembedded-core/commit/0e42326dfd6b9042b405329ceb56a93199a89a85) to upcoming Release 5.0 ("`scarthgap`").
Update layer compatibility to match OE-Core, and drop "`mickledore`" as according to [_Yocto Project Releases_](https://wiki.yoctoproject.org/wiki/Releases) it is indicated as EOL.

conf: layer: add 'scarthgap' to LAYERSERIES_COMPAT

---

classes-recipe/genimage.bbclass
conf/layer.conf

I'm not sure if this should go to master or a new scarthgap branch.
Closes: #131

bmaptool dependency fixup

---

classes-recipe/genimage.bbclass

Since nanbield [1], IMAGE_NAME and IMAGE_LINK_NAME include the IMAGE_NAME_SUFFIX, which means that the rootfs files gain an additional .rootfs suffix. Add support for this in genimage.
[1]: https://docs.yoctoproject.org/4.3.1/migration-guides/migration-4.3.html#output-file-naming-changes

genimage: support IMAGE_NAME_SUFFIX

---

recipes-bsp/barebox/barebox.inc

In scarthgap, lzop has been readded to poky with commit 07006c486722 ("Revert "lzop: remove recipe from oe-core""), readd it to the barebox depends to reallow lzop compression.
This reverts commit 38ada68c708d793eae99ace05dae1ba061fbfbdc.

barebox: readd lzop-native

---

classes-recipe/genimage.bbclass

Allow the recipe to set GENIMAGE_COMPRESSION to "gzip" or "xz". Other types are trivial to add support for if desired. Even if the class doesn't yet support a given scheme, the recipe itself can just define the proper GENIMAGE_COMPRESS_DEPENDS[foo] and
GENIMAGE_COMPRESS_CMD[foo].

genimage.bbclass: support compressing the generated image

---

classes-recipe/genimage.bbclass
conf/layer.conf
recipes-bsp/barebox/barebox.inc
recipes-core/ptx-profile/ptx-profile.bb
recipes-core/systemd/systemd-rc-once.bb

This adapts to the oe-core rework to enforce a separate directory for unpacking local sources (`UNPACKDIR`) instead of polluting `WORKDIR` directly.
Follows the preliminary guidelines from:
https://lists.openembedded.org/g/openembedded-architecture/message/2007
Removes compatibility with `scarthgap` and adds `styhead` instead.

follow WORKDIR -> UNPACKDIR transition 

---

classes-recipe/genimage.bbclass

Instead of randomly deleting some package tasks and setting some to `[noexec]`, use the `nopackages` class.

genimage.bbclass: use nopackages

---

classes-recipe/genimage.bbclass

These changes will notably impact how the `genimage.bbclass` performs.
They will
* save disk space (by removing sstate artifacts) 
* better trigger rebuilds where useful
* avoid unnecessary rebuilds
Fixes #130

genimage.bbclass: disable SSTATE artifact generation and avoid unnecessary rebuilds

---

classes-recipe/bootspec.bbclass

* Add documentation to the header
* use `[vardeps]` to fix rebuilds when changing `BOOTSPEC_` options
* refactor code for `BOOTSPEC_OPTIONS` default
* minor cleanups

bootspec.bbclass: Refactoring, Fixes and Documentation

---

recipes-devtools/genimage/genimage.inc

Sync the summary with the title in the project's README. Genimage got a dedicated `COPYING` file in 2016. Use it now.

genimage: update SUMMARY and LIC_FILES_CHKSUM

---

recipes-devtools/genimage/genimage.inc

It has never been a build dependency.

genimage: remove build dependency on dosfstools

---

recipes-devtools/confuse/confuse_3.3.bb
recipes-devtools/confuse/files/0001-only-apply-search-path-logic-to-relative-pathnames.patch

Contrary to my claim in meta-ptx commit 52d88c6c ("confuse: update to 3.3"), the patch was not part of v3.3, yet (but is part of master).
Thus re-add it and fix the Upstream-Status by replacing the now invalid 'Accepted' with 'Backport'.
Fixes #143

confuse: re-add search path patch dropped with the v3.3 update

---

recipes-bsp/barebox/barebox.inc

Default assign the BAREBOX_IMAGE_SUFFIX so it is easily overridable within a recipe.

barebox: default assign BAREBOX_IMAGE_SUFFIX

---

recipes-devtools/genimage/genimage.inc

genimage is hosted and released on [GitHub](https://github.com/pengutronix/genimage) now.

genimage: switch to GitHub URL and enable upstream check

---

recipes-devtools/genimage/genimage_17.bb
recipes-devtools/genimage/genimage_18.bb

This release includes https://github.com/pengutronix/genimage/pull/243 which changes from genext2fs to e2fsprogs/mke2fs as default for creating ext* images.
This will finally allow us to drop the recipe for genext2fs in a next step.

genimage: update to v18

---

classes-recipe/genimage.bbclass

* Note that a separate recipe is required for `genimage.bbclass`
* Add check if `genimage.bclass` is inherited in a rootfs image recipe
Related to #152

Clarify usage of genimage.bbclass

---

classes/genimage.bbclass

A genimage config may generate multiple images, either because multiple image { } clauses are specified or because an exec-post generated further images (e.g. image { exec-post = "gzip -k $IMAGEOUTFILE" })
We already deploy these extra images, but currently symlinks are only created for the plain image and for the bmap file. Make this more generic, so fixed symlinks are created at least for all images using @IMAGE@ as part of their filename.
Signed-off-by: Ahmad Fatoum <a.fatoum@pengutronix.de>
[ahmad: backport from 518d3c602ab524b9b6ea74152e7e563fb9804758]
---
I need this, because the BSP I work on has a sparse image with a name that keeps changing and I want a fixed symlink to point at it.

kirkstone-backport: classes: genimage: generalize image symlink creation

---

.github/workflows/build.yml

Scheduled builds only run for the main branch of a project, so configuring them on other release branches does not make a lot of sense.

styhead: .github/workflows/build: remove scheduled build

---

.github/workflows/build.yml
.github/workflows/schedule-builds.yml
README.md

We currently only test the master branch on a regular schedule and not the different release branches (like e.g. scarthgap or styhead).
Also testing these other branches is complicated by the following detail in the GitHub action [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule):
> Scheduled workflows will only run on the default branch
This means we need some sort of workaround to run scheduled jobs on different branches. This commit adds a scheduled job on the master branch to trigger jobs on other branches via the `workflow_dispatch` event.
Build the master branch as well as all current release branches.
This change is based on similar PRs in meta-rauc and meta-labgrid:
- …

.github/workflows/schedule-builds: Run scheduled jobs via workflow_dispatch

---

classes-recipe/genimage.bbclass
conf/layer.conf
recipes-core/ptx-profile/ptx-profile.bb
recipes-core/systemd/systemd-rc-once.bb
recipes-graphics/platsch/platsch_2024.08.0.bb

* remove `S = "${WORKDIR}/git"`
*  set `S` from `UNPACKDIR` in recipes that use only local files

Adapt S / UNPACKDIR handling and add 'whinlatter' to 'LAYERSERIES_COMPAT'
